[package]
name = "sub1"
version = "1.0.2"
autotests = false
autobins = false

[target.'cfg(target_os = "linux")'.dependencies]
sub2 = "1.2.*"

[target.'cfg(not(target_os = "linux"))'.dependencies]
sub2 = "1.2.*"
